apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-tracker
  labels:
    app: student-tracker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: student-tracker
  template:
    metadata:
      labels:
        app: student-tracker
    spec:
      containers:
        - name: student-tracker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: VAULT_ADDR
              valueFrom:
                secretKeyRef:
                  name: vault-secrets
                  key: VAULT_ADDR
            - name: VAULT_ROLE_ID
              valueFrom:
                secretKeyRef:
                  name: vault-secrets
                  key: VAULT_ROLE_ID
            - name: VAULT_SECRET_ID
              valueFrom:
                secretKeyRef:
                  name: vault-secrets
                  key: VAULT_SECRET_ID
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"