apiVersion: v1
kind: Service
metadata:
  name: student-tracker-service
spec:
  selector:
    app: student-tracker
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}