name: Shell Script Linting

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint scripts
        uses: ludeeus/action-shellcheck@v2
        with:
          args: scripts/*.sh
