name: Deploy Student Tracker from Docker Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_REPO: biwunor/student-tracker
  IMAGE_TAG: latest
  CLUSTER_NAME: student-tracker
  NAMESPACE: student-tracker
  EC2_DNS: ec2-54-170-56-216.eu-west-1.compute.amazonaws.com

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          config: k8s/kind-config.yaml

      - name: Wait for cluster to be ready
        run: |
          kubectl wait --for=condition=Ready node --all --timeout=120s

      - name: Create namespaces
        run: |
          kubectl create ns ingress-nginx || true
          kubectl create ns $NAMESPACE || true

      - name: Install ingress-nginx
        run: |
          kubectl apply --validate=false -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
          kubectl rollout status deployment/ingress-nginx-controller -n ingress-nginx --timeout=180s
          kubectl patch svc ingress-nginx-controller -n ingress-nginx --type='merge' -p '{"spec":{"type":"LoadBalancer"}}' || true

      - name: Deploy Helm chart using Docker image
        run: |
          helm upgrade --install student-tracker ./helm/student-tracker \
            --namespace $NAMESPACE --create-namespace \
            --set image.repository=$IMAGE_REPO \
            --set image.tag=$IMAGE_TAG \
            --set vault.VAULT_ADDR="http://44.204.193.107:8200" \
            --set vault.VAULT_ROLE_ID="f7af58b1-5c22-7c2d-c659-0425d9ce94b2" \
            --set vault.VAULT_SECRET_ID="d5f736da-785b-8f5c-9258-48d5d7c43c06" \
            --set ingress.host=${{ env.EC2_DNS }}

      - name: Check deployment
        run: |
          kubectl get all -n $NAMESPACE
          kubectl get ingress -n $NAMESPACE