name: Deploy Student Tracker with Helm & Tests

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_REPO: biwunor/student-tracker
  IMAGE_TAG: latest
  CLUSTER_NAME: student-tracker
  NAMESPACE: student-tracker
  EC2_DNS: ec2-54-170-56-216.eu-west-1.compute.amazonaws.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          config: k8s/kind-config.yaml

      - name: Wait for nodes ready
        run: kubectl wait --for=condition=Ready node --all --timeout=120s

      - name: Create namespaces
        run: |
          kubectl create ns ingress-nginx || true
          kubectl create ns $NAMESPACE || true

      - name: Install ingress-nginx controller
        run: |
          kubectl apply --validate=false -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
          kubectl rollout status deployment/ingress-nginx-controller -n ingress-nginx --timeout=180s
          kubectl patch svc ingress-nginx-controller -n ingress-nginx --type='merge' -p '{"spec":{"type":"LoadBalancer"}}' || true

      - name: Helm lint chart
        run: helm lint ./helm/student-tracker

      - name: Deploy Helm chart
        run: |
          helm upgrade --install student-tracker ./helm/student-tracker \
            --namespace $NAMESPACE --create-namespace \
            --set image.repository=$IMAGE_REPO \
            --set image.tag=$IMAGE_TAG \
            --set vault.VAULT_ADDR="http://44.204.193.107:8200" \
            --set vault.VAULT_ROLE_ID="f7af58b1-5c22-7c2d-c659-0425d9ce94b2" \
            --set vault.VAULT_SECRET_ID="d5f736da-785b-8f5c-9258-48d5d7c43c06" \
            --set ingress.host=$EC2_DNS

      - name: Wait for deployment rollout
        run: kubectl rollout status deployment/student-tracker -n $NAMESPACE --timeout=180s

      - name: Test HTTP endpoint
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" "http://$EC2_DNS")
          echo "HTTP Status Code: $STATUS_CODE"
          if [[ "$STATUS_CODE" =~ ^2 ]]; then
            echo "App is reachable!"
          else
            echo "App is NOT reachable!"
            exit 1
          fi

      - name: Slack Notification on success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "✅ Student Tracker deployed successfully!\nURL: http://${{ env.EC2_DNS }}"
      - name: Slack Notification on failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "❌ Student Tracker deployment failed.\nPlease check the GitHub Actions logs."